### ISSUE TITLE
[qplex_core.py] Could you please explain more how it works?

### ISSUE THREAD

**Issue by dongsin-kim** [gatchan00/QPlex#1]
Hi, I'm interested in the concept of QPLEX. (Is it from the solver IBM CPLEX right?) I already read 'README.md' but I can't totally figure the 'qplex_core.py' yet.

1. Could you please explain more about the functions in 'qplex_core.py'.

2. Could we extend the QPlex to solve as Non-linear Programming (NLP)?

**Comment by gatchan00** [comment]
Dear dongsin-kim,
First of all, thanks for your interest. Yep, it's based on IBM CPLEX, but still on an early development.
We tried to make a solver for generic functions receiving a function with different variables and a condition (currently condition is like  a*x+b*y+c*z <= beta). you can check an example at the main. 

We encode the number (integer) as binary on severl qbits (as many as precission specified). 

And of course you can extend QPlex, it has a MIT license, and if that helps you, we are delighted to know.¨

Regards

**Comment by dongsin-kim** [comment]
Dear gatchan00,
Hello.

Thank you for your reply-! Oh, I see. I am really surprised about your idea.

Maybe, I need more time to look into the code. I hope to keep in touch.

And I hope you have a great day. :-)

Best regards,
Dongsin

**Comment by gatchan00** [comment]
You are welcome, 

If you need something, just ask for it.

Regards
